### PR TITLE
Updated ERD : Caleb

### PR DESCRIPTION
**Pull request by CalebMathers**
For issue #104 

Made changes to the ERD; 
- now has only one timestamp field in body_assignment.
- added region and constellation ids to image to a star map can link correctly.
- added short name to constellation to make simpler API calls in the future.

### CODE REVIEW

**Comment by MurasatoNaoya** [comment]
Nice catch with the abbreviations, as that is what astronomyAPI is expecting.

**Review by MurasatoNaoya — APPROVED** [review]
LGTM, important changes for the ERD and how we will structure are data in the RDS post-meeting with the tech coaches.

**Review by AlexOBarnes — APPROVED** [review]
Great to see you using our feedback with @Ruyzambrano  to amend our ERD

**Comment by AlexOBarnes** [comment]
I appreciate your consideration for the validity and stringency of reliability of storing images in our database

**Review by olliejth — APPROVED** [review]
Changes in line with what we discussed

**Pull request merged**
