### PR TITLE
Updated ERD diagram : Caleb

### LINKED ISSUE #152: Update ERD
As a database designer, I want to create an Entity Relationship Diagram (ERD), so that I can visualize the database schema and the relationships between entities, in order to ensure a well-structured, efficient database design.

- Update schema to link constellation table to body_assignment

### PR DESCRIPTION
**Pull request by CalebMathers**
This closes #152 

Updated the ERD image in the assets directory to represent the agreed changes for storing the constellation id as a foreign key in body assignment rather than body so that it can be easily updated as bodies move in front of different constellations.

### CODE REVIEW

**Review by AlexOBarnes — COMMENTED** [review]
Interesting use of colour

**Comment by AlexOBarnes** [comment]
I like how the relationships are clearly shown

**Comment by AlexOBarnes** [comment]
Have you thought about different colours?

**Review by AlexOBarnes — APPROVED** [review]
Very useful changes

**Review by MurasatoNaoya — APPROVED** [review]
The StarWatch ERD now reflects the changes made to our RDS schema where constellation ID is no longer stored in the body table, but an assignment table for body. LGTM.

**Pull request merged**
