### PR TITLE
Updated ERD : Caleb

### LINKED ISSUE #169: Update ERD to include distance
As a database designer, I want to create an Entity Relationship Diagram (ERD), so that I can visualize the database schema and the relationships between entities, in order to ensure a well-structured, efficient database design.

- Update schema to include distance in body_assignment

### PR DESCRIPTION
**Pull request by CalebMathers**
This closes #169 

Reflected the changes in the ERD:
- Added distance_km (float) to body_assignment
- Changed datatype for visibility_m in forecast from smallint to int
- Made possible NULL values visible in the ERD

### CODE REVIEW

**Review by MurasatoNaoya — APPROVED** [review]
Noice. The ERD now clearly reflects the changes made to the database schema, ie adding distance to the _body_assignment_  table.

**Comment by AlexOBarnes** [comment]
I really like how we are amending things for our stakeholders

**Comment by AlexOBarnes** [comment]
Always keep our audience in mind

**Comment by AlexOBarnes** [comment]
Great work!

**Pull request merged**
